<a href="https://colab.research.google.com/github/ABeatrizSC/Analise-De-Dados-com-Python/blob/main/AnaliseDeDados.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Análise de Dados com Python

### Desafio:

Você trabalha em uma empresa de telecom e tem clientes de vários serviços diferentes, entre os principais: internet e telefone.

O problema é que, analisando o histórico dos clientes dos últimos anos, você percebeu que a empresa está com Churn de mais de 26% dos clientes.

Isso representa uma perda de milhões para a empresa.

O que a empresa precisa fazer para resolver isso?

Base de Dados: https://drive.google.com/drive/folders/1T7D0BlWkNuy_MDpUHuBG44kT80EmRYIs?usp=sharing <br>
Link Original do Kaggle: https://www.kaggle.com/radmirzosimov/telecom-users-dataset

In [ ]:
# Passo 1: Importar a base de dados
import pandas as pd

tabela = pd.read_csv('telecom_users.csv') #variável recebe a tabela que tem como extensão o CSV (ex: ou HTML, SQL, EXCEL)

# Passo 2: Visualizar a base de dados
#display(tabela) #Exibir tabela para analisá-la
# - Entender quais as informações tão disponíveis
# - Descobrir os erros da base de dados

#Excluir colunas inúteis ao que precisamos
#axis = 0 -> eixo da linha
#axis = 1 -> eixo da coluna
tabela = tabela.drop('Unnamed: 0', axis=1) #Tabela irá receber a Tabela, dropando a coluna/linha entre os parenteses
display(tabela) #Exibir de novo para ver se deu certo.

,IDCliente,Genero,Aposentado,Casado,Dependentes,MesesComoCliente,ServicoTelefone,MultiplasLinhas,ServicoInternet,ServicoSegurancaOnline,...,ServicoSuporteTecnico,ServicoStreamingTV,ServicoFilmes,TipoContrato,FaturaDigital,FormaPagamento,ValorMensal,TotalGasto,Churn,Codigo
0,7010-BRBUU,Masculino,0,Sim,Sim,72,Sim,Sim,Nao,SemInternet,...,SemInternet,SemInternet,SemInternet,2 anos,Nao,CartaoCredito,24.10,1734.65,Nao,NaN
1,9688-YGXVR,Feminino,0,Nao,Nao,44,Sim,Nao,Fibra,Nao,...,Nao,Sim,Nao,Mensal,Sim,CartaoCredito,88.15,3973.2,Nao,NaN
2,9286-DOJGF,Feminino,1,Sim,Nao,38,Sim,Sim,Fibra,Nao,...,Nao,Nao,Nao,Mensal,Sim,DebitoAutomatico,74.95,2869.85,Sim,NaN
3,6994-KERXL,Masculino,0,Nao,Nao,4,Sim,Nao,DSL,Nao,...,Nao,Nao,Sim,Mensal,Sim,BoletoEletronico,55.90,238.5,Nao,NaN
4,2181-UAESM,Masculino,0,Nao,Nao,2,Sim,Nao,DSL,Sim,...,Nao,Nao,Nao,Mensal,Nao,BoletoEletronico,53.45,119.5,Nao,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5981,0684-AOSIH,Masculino,0,Sim,Nao,1,Sim,Nao,Fibra,Sim,...,Nao,Sim,Sim,Mensal,Sim,BoletoEletronico,95.00,95,Sim,NaN
5982,5982-PSMKW,Feminino,0,Sim,Sim,23,Sim,Sim,DSL,Sim,...,Sim,Sim,Sim,2 anos,Sim,CartaoCredito,91.10,2198.3,Nao,NaN
5983,8044-BGWPI,Masculino,0,Sim,Sim,12,Sim,Nao,Nao,SemInternet,...,SemInternet,SemInternet,SemInternet,Mensal,Sim,BoletoEletronico,21.15,306.05,Nao,NaN
5984,7450-NWRTR,Masculino,1,Nao,Nao,12,Sim,Sim,Fibra,Nao,...,Nao,Sim,Sim,Mensal,Sim,BoletoEletronico,99.45,1200.15,Sim,NaN
5985,4795-UXVCJ,Masculino,0,Nao,Nao,26,Sim,Nao,Nao,SemInternet,...,SemInternet,SemInternet,SemInternet,Anual,Nao,CartaoCredito,19.80,457.3,Nao,NaN

In [ ]:
# Passo 3: Tratamento de dados
# print(tabela.info()) #EXIBIR: Resumo de como está sua sua Base de Dados (Valores nulos, seus tipos de dados, numero de colunas e linhas e etc...)

#Primeiro: Analisar e consertar os valores que estão reconhecidos de forma errada
tabela["TotalGasto"] = pd.to_numeric(tabela["TotalGasto"], errors="coerce") #Mudando o Tipo da coluna 'Total Gastos' para float

# Segundo: Tirando valores vazios (nulos)
# print(tabela.info()) #EXIBIR para ver onde tem valores nulos

# deletando as colunas que estão TOTALMENTE VAZIAS
# axis = 0 _> linha
# axis = 1 _> coluna
tabela = tabela.dropna(how="all", axis=1)
#colunas totoalmente vazias serão jogadas fora


# deletando as linhas que possuem em algum lugar, uma informação vazia.
#Não há problema em deletá-las, pois foi visto através do .info() que são poucas em relação ao total.
tabela = tabela.dropna(how="any", axis=0)
#se a linha tiver pelo menos UM valor vazio, será descartada

print(tabela.info())

<class 'pandas.core.frame.DataFrame'>
Int64Index: 5974 entries, 0 to 5985
Data columns (total 21 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   IDCliente               5974 non-null   object
 1   Genero                  5974 non-null   object
 2   Aposentado              5974 non-null   int64
 3   Casado                  5974 non-null   object
 4   Dependentes             5974 non-null   object
 5   MesesComoCliente        5974 non-null   int64
 6   ServicoTelefone         5974 non-null   object
 7   MultiplasLinhas         5974 non-null   object
 8   ServicoInternet         5974 non-null   object
 9   ServicoSegurancaOnline  5974 non-null   object
 10  ServicoBackupOnline     5974 non-null   object
 11  ProtecaoEquipamento     5974 non-null   object
 12  ServicoSuporteTecnico   5974 non-null   object
 13  ServicoStreamingTV      5974 non-null   object
 14  ServicoFilmes           5974 non-null   object
 15  TipoContrato            5974 non-null   object
 16  FaturaDigital           5974 non-null   object
 17  FormaPagamento          5974 non-null   object
 18  ValorMensal             5974 non-null   float64
 19  TotalGasto              5974 non-null   float64
 20  Churn                   5974 non-null   object
dtypes: float64(2), int64(2), object(17)
memory usage: 1.0+ MB
None

In [ ]:
# Passo 4: Análise Inicial
# Como estão os nossos cancelamentos?
print(tabela["Churn"].value_counts()) #Contar quantos cancelaram ou não, utilizando a coluna 'Churn'
print(tabela["Churn"].value_counts(normalize=True).map("{:.1%}".format)) #Formato para aparecer em PORCENTAGEM

Nao    4387
Sim    1587
Name: Churn, dtype: int64
Nao    73.4%
Sim    26.6%
Name: Churn, dtype: object

In [ ]:
# Passo 5: Análise Mais completa (comparar cada coluna da minha tabela com a coluna de cancelamento)
import plotly.express as px #Biblioteca para criar gráficos em Python

# etapa 1: criar o gráfico, para ficar mais fácil de visualizar as informações
for coluna in tabela.columns: #Compara as colunas com a coluna de cancelamento
    # para edições nos gráficos: https://plotly.com/python/histograms/ -> MOSTRA OS TIPOS DE GRÁFICOS
    # para mudar a cor do gráfico , color_discrete_sequence=["blue", "green"]
    grafico = px.histogram(tabela, x=coluna, color="Churn", text_auto=True)   
    # etapa 2: exibir o gráfico:
    grafico.show()

In [ ]:
# !pip install plotly #plotly instalado